---
- hosts: localhost
  connection: local

  tasks:

  - name: Create the non-root user account
    user:
      name: host
      shell: /bin/bash
      groups: sudo
      append: yes
      generate_ssh_key: yes
      ssh_key_comment: host@master

  - name: Add same SSH keys as root has
    authorized_key:
      user: host
      state: present
      key: "{{ item }}"
    with_lines: cat /root/.ssh/authorized_keys

  - name: Upgrading all packages
    apt:
      update_cache: yes
      upgrade: yes
 
  - name: Add the HashiCorp GPG key
    apt_key:
      url: https://apt.releases.hashicorp.com/gpg

  - name: Add the official HashiCorp Terraform Linux repository
    apt_repository:
      repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts.distribution_release }} main

  - name: Install Terraform
    apt:
      name: terraform

  - name: Copy token to user host
    copy:
      remote_src: yes
      src: /root/do_token
      dest: /home/host/do_token
      owner: host
      mode: 0600
